"""update user schema with corrected fields

Revision ID: 0acec3d6ebee
Revises: 3f4f4a8e09d0
Create Date: 2026-03-04 23:22:10.768292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0acec3d6ebee'
down_revision: Union[str, Sequence[str], None] = '3f4f4a8e09d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
