"""final steps

Revision ID: 46be4312b91d
Revises: 1737ac0f7cde
Create Date: 2026-03-12 03:04:00.255154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46be4312b91d'
down_revision: Union[str, Sequence[str], None] = '1737ac0f7cde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_unique_constraint(None, 'payments', ['booking_id'])
    op.create_unique_constraint(None, 'payments', ['transaction_ref'])
    op.create_unique_constraint(None, 'providers', ['user_id'])
    op.add_column('services', sa.Column('provider_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'services', 'providers', ['provider_id'], ['uid'])
    op.drop_column('services', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_column('services', 'provider_id')
    op.drop_constraint(None, 'providers', type_='unique')
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_table('notifications')
    # ### end Alembic commands ###
