"""add missing model fields

Revision ID: aff9a3246830
Revises: 46be4312b91d
Create Date: 2026-03-13 01:09:09.988586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aff9a3246830'
down_revision: Union[str, Sequence[str], None] = '46be4312b91d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('services', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'updated_at')
    op.drop_column('reviews', 'updated_at')
    # ### end Alembic commands ###
