"""add booking cancelled notification type

Revision ID: f46616739158
Revises: 481b35e0f415
Create Date: 2026-05-04 14:36:36.951015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f46616739158'
down_revision: Union[str, Sequence[str], None] = '481b35e0f415'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('disputes', sa.Column('resolution', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('disputes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.execute('TRUNCATE TABLE notifications')
    op.add_column('notifications', sa.Column('notification_type', sa.VARCHAR(), nullable=False, server_default=''))
    op.add_column('notifications', sa.Column('user_uid', sa.Uuid(), nullable=False, server_default='00000000-0000-0000-0000-000000000000'))
    op.alter_column('notifications', 'notification_type', server_default=None)
    op.alter_column('notifications', 'user_uid', server_default=None)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(op.f('notifications_user_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_uid'], ['uid'])
    op.drop_column('notifications', 'event_type')
    op.drop_column('notifications', 'entity_type')
    op.drop_column('notifications', 'title')
    op.drop_column('notifications', 'user_id')
    op.drop_column('notifications', 'payload')
    op.drop_column('notifications', 'entity_id')
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('providers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('reviews', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    op.alter_column('reviews', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('providers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('notifications', sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('entity_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('event_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_user_id_fkey'), 'notifications', 'users', ['user_id'], ['uid'])
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('notifications', 'user_uid')
    op.drop_column('notifications', 'notification_type')
    op.alter_column('disputes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('disputes', 'resolution')
    op.alter_column('bookings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
