"""added improved models

Revision ID: 1737ac0f7cde
Revises: 41cd18739f8d
Create Date: 2026-03-10 00:39:20.745261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1737ac0f7cde'
down_revision: Union[str, Sequence[str], None] = '41cd18739f8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('booking_date', sa.DateTime(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('providers',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('business_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('disputes',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('raised_by', sa.Uuid(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('admin_response', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.uid'], ),
    sa.ForeignKeyConstraint(['raised_by'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('payments',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transaction_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.add_column('reviews', sa.Column('booking_id', sa.Uuid(), nullable=False))
    op.add_column('reviews', sa.Column('reviewer_id', sa.Uuid(), nullable=False))
    op.alter_column('reviews', 'comment',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.alter_column('reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'reviews', 'users', ['reviewer_id'], ['uid'])
    op.create_foreign_key(None, 'reviews', 'bookings', ['booking_id'], ['uid'])
    op.drop_column('reviews', 'user_id')
    op.drop_column('reviews', 'service_id')
    op.drop_column('reviews', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('reviews', sa.Column('service_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('reviews', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.alter_column('reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('reviews', 'comment',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.drop_column('reviews', 'reviewer_id')
    op.drop_column('reviews', 'booking_id')
    op.drop_table('payments')
    op.drop_table('disputes')
    op.drop_table('providers')
    op.drop_table('bookings')
    # ### end Alembic commands ###
