"""worked on the notifications

Revision ID: 40eaa155f504
Revises: d2c4f9a1b8e7
Create Date: 2026-03-28 12:32:38.472527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '40eaa155f504'
down_revision: Union[str, Sequence[str], None] = 'd2c4f9a1b8e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_user_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_is_read'), table_name='notifications')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_notifications_user_is_read'), 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_created_at'), 'notifications', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###
