"""worked on the email

Revision ID: 481b35e0f415
Revises: c1d9e8a5f2b4
Create Date: 2026-03-28 17:24:41.205148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '481b35e0f415'
down_revision: Union[str, Sequence[str], None] = 'c1d9e8a5f2b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_deleted_at'), table_name='bookings')
    op.drop_index(op.f('ix_reviews_deleted_at'), table_name='reviews')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_reviews_deleted_at'), 'reviews', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_bookings_deleted_at'), 'bookings', ['deleted_at'], unique=False)
    # ### end Alembic commands ###
